This notebook covers reading and writing JSON files using Python's standard library and pandas, then working with SQL databases using `sqlite3` (built-in) and SQLAlchemy.

**Sections**
1. JSON : standard library `json` module + `pd.read_json()` + nested JSON
2. SQL Part 1 : Basics with `sqlite3`
3. SQL Part 2 : Moderate: INSERT, parameterized queries, `.sql` files
4. SQL Part 3 : Advanced: transactions, error handling, SQLAlchemy

## Setup

Run this cell first to confirm required files are present.

In [5]:
import os, json
import pandas as pd

In [7]:
files = ['data/products.json']
for f in files:
    print("OK " if os.path.exists(f) else "MISSING ", f)

OK  data/products.json

### **JSON**

### **Standard Library: `json` module**

| Function | What it does |
|----------|--------------|
| `json.load(fp)` | Read JSON from a file object → Python object |
| `json.loads(s)` | Parse a JSON string → Python object |
| `json.dump(obj, fp)` | Write Python object as JSON to a file |
| `json.dumps(obj)` | Serialize Python object to a JSON string |

Key parameters for `json.dump` / `json.dumps`:
- `indent` : pretty-print with N-space indentation
- `sort_keys` : alphabetize keys
- `default` : callable for objects that aren't JSON-serializable

In [11]:
import json

# json.load to read from file
with open('data/products.json') as f:
    products = json.load(f)

print(type(products))        # list
print(f"Loaded {len(products)} products")
print(products[0])

<class 'list'>
Loaded 3 products
{'id': 1, 'name': 'Laptop', 'price': 999.99, 'category': 'Electronics', 'specs': {'ram': '16GB', 'storage': '512GB'}}

In [13]:
# json.loads to parse a string
json_str = '{"name": "Widget", "price": 9.99, "in_stock": true}'
obj = json.loads(json_str)

print(obj)
print(type(obj['in_stock']))

{'name': 'Widget', 'price': 9.99, 'in_stock': True}
<class 'bool'>

In [15]:
# json.dumps - serialize with formatting options
print("Compact (default):")
print(json.dumps(products[0]))

print("\nPretty-printed (indent=2):")
print(json.dumps(products[0], indent=2))

print("\nSorted keys:")
print(json.dumps(products[0], indent=2, sort_keys=True))

Compact (default):
{"id": 1, "name": "Laptop", "price": 999.99, "category": "Electronics", "specs": {"ram": "16GB", "storage": "512GB"}}

Pretty-printed (indent=2):
{
  "id": 1,
  "name": "Laptop",
  "price": 999.99,
  "category": "Electronics",
  "specs": {
    "ram": "16GB",
    "storage": "512GB"
  }
}

Sorted keys:
{
  "category": "Electronics",
  "id": 1,
  "name": "Laptop",
  "price": 999.99,
  "specs": {
    "ram": "16GB",
    "storage": "512GB"
  }
}

In [17]:
# json.dump to write to file
output = {"exported_at": "2026-06-11", "count": len(products), "data": products}

with open('data/products_export.json', 'w') as f:
    json.dump(output, f, indent=2)
print("Written to data/products_export.json")

Written to data/products_export.json

In [19]:
# default parameter to handle non-serializable types
import datetime

record = {
    "name": "Alice",
    "hired": datetime.date(2020, 1, 15),   # not JSON-serializable by default
    "salary": 85000,
}

def serialize_date(obj):
    if isinstance(obj, (datetime.date, datetime.datetime)):
        return obj.isoformat()
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")

print(json.dumps(record, default=serialize_date, indent=2))

{
  "name": "Alice",
  "hired": "2020-01-15",
  "salary": 85000
}

### Pandas `pd.read_json()`

| Parameter | Default | What it does |
|-----------|---------|--------------|
| `orient` | inferred | Shape of JSON: `'records'`, `'columns'`, `'index'`, `'split'`, `'table'` |
| `lines` | `False` | Each line is a separate JSON object (JSONL format) |
| `dtype` | `True` | Infer dtypes; pass dict to force specific types |
| `convert_dates` | `True` | Auto-parse columns that look like dates |

In [21]:
import pandas as pd

# Default
df = pd.read_json('data/products.json')
print("Shape:", df.shape)
df

Shape: (3, 5)

,id,name,price,category,specs
0,1,Laptop,999.99,Electronics,"{'ram': '16GB', 'storage': '512GB'}"
1,2,Desk Chair,299.99,Furniture,"{'color': 'Black', 'material': 'Leather'}"
2,3,Coffee Maker,79.99,Appliances,"{'cups': 12, 'programmable': True}"

In [23]:
# orient='records' is explicit default for list-of-dicts files
df2 = pd.read_json('data/products.json', orient='records')
print(df2.dtypes)

id            int64
name         object
price       float64
category     object
specs        object
dtype: object

In [25]:
# lines=True - JSONL format (one JSON object per line)
import io
jsonl = '{"name":"Alice","age":30}\n{"name":"Bob","age":25}\n'
df_lines = pd.read_json(io.StringIO(jsonl), lines=True)
print(df_lines)

    name  age
0  Alice   30
1    Bob   25

### Handling Nested JSON with `pd.json_normalize()`

When JSON contains nested objects, `pd.json_normalize()` flattens them into columns.
The `sep` parameter controls how nested key names are joined (default `'.'`).

In [27]:
# Flatten nested 'specs' dict inside each product
df_flat = pd.json_normalize(products, sep='_')
print("Columns after normalization:")
print(df_flat.columns.tolist())
df_flat

Columns after normalization:
['id', 'name', 'price', 'category', 'specs_ram', 'specs_storage', 'specs_color', 'specs_material', 'specs_cups', 'specs_programmable']

,id,name,price,category,specs_ram,specs_storage,specs_color,specs_material,specs_cups,specs_programmable
0,1,Laptop,999.99,Electronics,16GB,512GB,NaN,NaN,NaN,NaN
1,2,Desk Chair,299.99,Furniture,NaN,NaN,Black,Leather,NaN,NaN
2,3,Coffee Maker,79.99,Appliances,NaN,NaN,NaN,NaN,12.0,True

In [29]:
# Nested list of records inside a parent key
data = {
    "company": "Acme",
    "employees": [
        {"name": "Alice", "skills": ["Python", "SQL"]},
        {"name": "Bob",   "skills": ["Excel", "R"]},
    ]
}
df_nested = pd.json_normalize(
    data,
    record_path='employees',   # which key contains the list to explode
    meta=['company'],           # parent-level fields to carry over
)
print(df_nested)

    name         skills company
0  Alice  [Python, SQL]    Acme
1    Bob     [Excel, R]    Acme

---

### **SQL Part 1: Basics with `sqlite3`**

SQLite is a file-based database built into Python. No server needed. The `sqlite3` standard library module is the interface.

**Key objects:**
- `Connection` : represents the database file
- `Cursor` : executes SQL and holds results

In [32]:
import sqlite3
import pandas as pd
import os

DB_PATH = 'data/company.db'

# Connect (creates file if it doesn't exist)
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
print("Connected to:", DB_PATH)
print("SQLite version:", sqlite3.sqlite_version)

Connected to: data/company.db
SQLite version: 3.51.1

In [34]:
# CREATE TABLE
cursor.execute("""
    CREATE TABLE IF NOT EXISTS employees (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        name      TEXT    NOT NULL,
        age       INTEGER,
        city      TEXT,
        salary    REAL,
        department TEXT,
        start_date TEXT
    )
""")
conn.commit()
print("Table created (or already exists)")

Table created (or already exists)

In [38]:
# INSERT rows (guard against duplicates on re-run)
cursor.execute("SELECT COUNT(*) FROM employees")
if cursor.fetchone()[0] == 0:
    rows = [
        ('Alice',   30, 'New York',      85000, 'Engineering', '2020-01-15'),
        ('Bob',     25, 'San Francisco', 72000, 'Marketing',   '2021-06-01'),
        ('Charlie', 35, 'Chicago',       95000, 'Engineering', '2019-03-20'),
        ('Diana',   28, 'New York',      68000, 'HR',          '2022-02-10'),
        ('Eve',     32, 'Boston',        88000, 'Engineering', '2020-11-05'),
    ]
    cursor.executemany(
        "INSERT INTO employees (name, age, city, salary, department, start_date) VALUES (?,?,?,?,?,?)",
        rows
    )
    conn.commit()
    print(f"Inserted {len(rows)} rows")
else:
    print("Table already has data, hence we skip inserting the data")

Table already has data, hence we skip inserting the data

In [42]:
# SELECT with fetchall
cursor.execute("SELECT * FROM employees WHERE department = 'Engineering'")
results = cursor.fetchall()
print("Engineering employees:")
for row in results:
    print(row)

Engineering employees:
(1, 'Alice', 30, 'New York', 113135.00000000004, 'Engineering', '2020-01-15')
(3, 'Charlie', 35, 'Chicago', 126445.00000000004, 'Engineering', '2019-03-20')
(5, 'Eve', 32, 'Boston', 117128.00000000004, 'Engineering', '2020-11-05')
(7, 'Grace', 29, 'New York', 110110.00000000003, 'Engineering', '2020-07-01')

In [44]:
# SELECT into a pandas DataFrame — the most common workflow
df = pd.read_sql("SELECT * FROM employees ORDER BY salary DESC", conn)
print(df)

   id     name   age           city    salary   department  start_date
0   3  Charlie  35.0        Chicago  126445.0  Engineering  2019-03-20
1   5      Eve  32.0         Boston  117128.0  Engineering  2020-11-05
2   1    Alice  30.0       New York  113135.0  Engineering  2020-01-15
3   7    Grace  29.0       New York  110110.0  Engineering  2020-07-01
4   6    Frank   NaN         Austin   76000.0    Marketing  2021-09-15
5   2      Bob  25.0  San Francisco   72000.0    Marketing  2021-06-01
6   4    Diana  28.0       New York   68000.0           HR  2022-02-10

In [46]:
# fetchone and fetchmany
cursor.execute("SELECT name, salary FROM employees ORDER BY salary DESC")
print("Top earner:", cursor.fetchone())
print("Next two:  ", cursor.fetchmany(2))

Top earner: ('Charlie', 126445.00000000004)
Next two:   [('Eve', 117128.00000000004), ('Alice', 113135.00000000004)]

In [48]:
# Column names from cursor.description
cursor.execute("SELECT * FROM employees LIMIT 1")
columns = [desc[0] for desc in cursor.description]
print("Column names:", columns)

Column names: ['id', 'name', 'age', 'city', 'salary', 'department', 'start_date']

---

### **SQL Part 2: Moderate**

Covers INSERT, UPDATE, reading from `.sql` files, and parameterized queries.

In [51]:
import sqlite3

conn = sqlite3.connect('data/company.db')
cursor = conn.cursor()

# Read and execute a .sql file
with open('data/setup.sql') as f:
    sql_script = f.read()

cursor.executescript(sql_script)
print("SQL file executed successfully")

cursor.execute("SELECT * FROM departments")
print(cursor.fetchall())

SQL file executed successfully
[(1, 'Engineering', 400000.0), (2, 'Marketing', 200000.0), (3, 'HR', 250000.0)]

In [59]:
# UPDATE - give Engineering a 10% raise
cursor.execute("""
    UPDATE employees
    SET salary = salary * 1.10
    WHERE department = 'Engineering'
""")
conn.commit()
print(f"Rows updated: {cursor.rowcount}")

df = pd.read_sql("SELECT name, salary, department FROM employees ORDER BY department", conn)
print(df)

Rows updated: 4
      name       salary   department
0    Alice  165640.9535  Engineering
1  Charlie  185128.1245  Engineering
2      Eve  171487.1048  Engineering
3    Grace  161212.0510  Engineering
4    Diana   68000.0000           HR
5      Bob   72000.0000    Marketing
6    Frank   76000.0000    Marketing

### Parameterized Queries

Always use `?` placeholders instead of f-strings to prevent SQL injection.

In [62]:
# BAD, never do this (SQL injection risk)
# name_input = "Alice'; DROP TABLE employees;--"
# cursor.execute(f"SELECT * FROM employees WHERE name = '{name_input}'")

# GOOD - parameterized query with ?
name_input = 'Alice'
cursor.execute("SELECT * FROM employees WHERE name = ?", (name_input,))
print("Parameterized result:", cursor.fetchone())

Parameterized result: (1, 'Alice', 30, 'New York', 165640.95350000012, 'Engineering', '2020-01-15')

In [64]:
# Multiple parameters
cursor.execute(
    "SELECT name, salary FROM employees WHERE department = ? AND salary > ?",
    ('Engineering', 80000)
)
print("Engineering employees earning > 80k:")
for row in cursor.fetchall():
    print(row)

Engineering employees earning > 80k:
('Alice', 165640.95350000012)
('Charlie', 185128.12450000012)
('Eve', 171487.10480000012)
('Grace', 161212.05100000012)

In [66]:
# executemany — batch INSERT of new employees
# Check first to avoid duplicates
cursor.execute("SELECT COUNT(*) FROM employees WHERE name IN ('Frank', 'Grace')")
if cursor.fetchone()[0] == 0:
    new_employees = [
        ('Frank', None, 'Austin',   76000, 'Marketing',   '2021-09-15'),
        ('Grace',  29,  'New York', 91000, 'Engineering', '2020-07-01'),
    ]
    cursor.executemany(
        "INSERT INTO employees (name, age, city, salary, department, start_date) VALUES (?,?,?,?,?,?)",
        new_employees
    )
    conn.commit()
    print(f"Batch inserted {cursor.rowcount} rows")
else:
    print("Frank and Grace already exist, skipping insert")

print("Total employees:", pd.read_sql("SELECT COUNT(*) AS n FROM employees", conn).iloc[0,0])

Frank and Grace already exist, skipping insert
Total employees: 7

---

### **SQL Part 3: Advanced**

Covers error handling, transactions, SQLAlchemy, and `pd.read_sql()` / `df.to_sql()`.

### Error Handling with `try/except`

In [69]:
import sqlite3

conn = sqlite3.connect('data/company.db')
cursor = conn.cursor()

try:
    # This will fail - inserting a duplicate primary key
    cursor.execute("INSERT INTO departments (id, name) VALUES (1, 'Duplicate')")
    conn.commit()
    print("Inserted (unexpected)")
except sqlite3.IntegrityError as e:
    conn.rollback()
    print(f"IntegrityError caught: {e}")
except sqlite3.OperationalError as e:
    conn.rollback()
    print(f"OperationalError caught: {e}")
finally:
    print("Connection still open:", conn is not None)

IntegrityError caught: UNIQUE constraint failed: departments.id
Connection still open: True

### Transactions : `commit()` and `rollback()`

A transaction groups multiple SQL operations so they succeed or fail together. If anything goes wrong, `rollback()` undoes all operations since the last `commit()`.

In [72]:
import pandas as pd

def transfer_budget(conn, from_dept_id, to_dept_id, amount):
    cursor = conn.cursor()
    try:
        cursor.execute(
            "UPDATE departments SET budget = budget - ? WHERE id = ?",
            (amount, from_dept_id)
        )
        # Simulated error mid-transaction
        if amount > 1_000_000:
            raise ValueError("Transfer amount exceeds limit")
        cursor.execute(
            "UPDATE departments SET budget = budget + ? WHERE id = ?",
            (amount, to_dept_id)
        )
        conn.commit()
        print(f"Transferred ${amount:,} from dept {from_dept_id} to dept {to_dept_id}")
    except Exception as e:
        conn.rollback()
        print(f"Transfer failed, rolled back: {e}")

# Successful transfer
transfer_budget(conn, from_dept_id=1, to_dept_id=3, amount=50000)

# Failed transfer — rollback
transfer_budget(conn, from_dept_id=1, to_dept_id=3, amount=5_000_000)

print(pd.read_sql("SELECT * FROM departments", conn))

Transferred $50,000 from dept 1 to dept 3
Transfer failed, rolled back: Transfer amount exceeds limit
   id         name    budget
0   1  Engineering  350000.0
1   2    Marketing  200000.0
2   3           HR  300000.0

### SQLAlchemy : Connecting to Other Databases

`sqlalchemy` provides a unified API for SQLite, PostgreSQL, MySQL, and more. The connection string format: `dialect+driver://user:password@host:port/database`

| Database   | Connection string |
|------------|------------------|
| SQLite     | `sqlite:///path/to/file.db` |
| PostgreSQL | `postgresql://user:pass@localhost:5432/dbname` |
| MySQL      | `mysql+pymysql://user:pass@localhost:3306/dbname` |

In [75]:
from sqlalchemy import create_engine
import pandas as pd

# SQLite via SQLAlchemy (same database, different interface)
engine = create_engine('sqlite:///data/company.db')

# Read with pd.read_sql, works with SQLAlchemy engine or sqlite3 connection
df = pd.read_sql("SELECT * FROM employees ORDER BY salary DESC", engine)
print("Via SQLAlchemy engine:")
print(df.head(3))

Via SQLAlchemy engine:
   id     name   age      city       salary   department  start_date
0   3  Charlie  35.0   Chicago  185128.1245  Engineering  2019-03-20
1   5      Eve  32.0    Boston  171487.1048  Engineering  2020-11-05
2   1    Alice  30.0  New York  165640.9535  Engineering  2020-01-15

In [77]:
# df.to_sql, write a DataFrame to a database table
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('sqlite:///data/company.db')

# Create a summary DataFrame and write it to a new table
df_summary = pd.read_sql("""
    SELECT department,
           COUNT(*)      AS headcount,
           AVG(salary)   AS avg_salary,
           MAX(salary)   AS max_salary
    FROM employees
    GROUP BY department
""", engine)

df_summary.to_sql(
    name='dept_summary',
    con=engine,
    if_exists='replace',   # 'replace', 'append', or 'fail'
    index=False,
)
print("dept_summary table created")
print(pd.read_sql("SELECT * FROM dept_summary", engine))

dept_summary table created
    department  headcount    avg_salary   max_salary
0  Engineering          4  170867.05845  185128.1245
1           HR          1   68000.00000   68000.0000
2    Marketing          2   74000.00000   76000.0000

In [79]:
# SQLAlchemy text() for parameterized queries via engine
from sqlalchemy import text

with engine.connect() as c:
    result = c.execute(
        text("SELECT name, salary FROM employees WHERE department = :dept AND salary > :min_sal"),
        {"dept": "Engineering", "min_sal": 85000}
    )
    for row in result:
        print(row)

('Alice', 165640.95350000012)
('Charlie', 185128.12450000012)
('Eve', 171487.10480000012)
('Grace', 161212.05100000012)

In [81]:
# Clean up and list all tables
conn.close()
print("sqlite3 connection closed")

with engine.connect() as c:
    tables = c.execute(text("SELECT name FROM sqlite_master WHERE type='table'")).fetchall()
    print("Tables in company.db:", [t[0] for t in tables])

sqlite3 connection closed
Tables in company.db: ['employees', 'sqlite_sequence', 'departments', 'dept_summary']